#!/usr/bin/env bash
GLOBIGNORE="*"
# for a domain you own hosted at namecheap, register one or more subdomains
# to an IP address in namecheaps dynamicdns system

if [ -r $(dirname "$0")/.env ]; then
  echo "Sourcing .env file at the same dir"
  source $(dirname "$0")/.env
elif [ -r ~/.namecheap-ddns-update ]; then
  echo "Sourcing user ($USER) .namecheap-ddns-update file"
  source ~/.namecheap-ddns-update
fi

# Update the domain subdomains
update() {
  while IFS=',' read -ra SUBDOMAIN_ARRAY; do
    for raw_subdomain in "${SUBDOMAIN_ARRAY[@]}"; do
      SUBDOMAIN="$(echo -e $raw_subdomain | tr -d '[[:space:]]')"
      echo "Registering subdomain: $SUBDOMAIN.$DOMAIN, to IP address: $IP"
      URL="$BASE_URL&host=$SUBDOMAIN"
      RESP="$(curl --silent --connect-timeout 10 $URL)"
      error_msg="$(echo -e $RESP | gawk '{ match($0, /<ErrCount>(.*)<\/ErrCount>.+<Err1>(.*)<\/Err1>/, arr); if (arr[1] > 0 ) print arr[2] }')"
      if [ "$error_msg" ]; then
        echo "ERROR : $error_msg" 1>&2;
        if [ "$EXIT_ON_ERROR" = true ]; then
          exit 1
        fi
      else
        new_ip="$(echo -e $RESP | gawk '{ match($0, /<IP>(.*)<\/IP>/, arr); if (arr[1] != "" ) print arr[1] }')"
        echo "$SUBDOMAIN.$DOMAIN IP address updated to: $new_ip"
      fi
    done
  done <<< "$SUBDOMAINS"
 }

# Usage info
show_help() {
cat << EOF

Usage: ${0##*/} [-h] [-e] [-d DOMAIN] [-s SUBDOMAINS] [-i IP] [-t INTERVAL]
Update the IP address of one or more subdomains, of a domain you own at
namecheap.com. This can only update an existing A record, it cannot create
a new A record. Use namecheap's advanced DNS settings for your domain to
create A records. The args d, s, i and t have corresponding ENV options. The
Dynamice DNS Password has to be set with the NC_DDNS_PASS environment variable.
You could also create an environment file in the same directory as the script,
called .env, or in directory of the user running this script, called
.namecheap-ddns-update. The .env file is sourced first if found, if it does
not exist, then .namecheap-ddns-update sourced if found.

    -h             display this help and exit
    -e             exit if any call to update a subdomains IP address fails
    -d DOMAIN      the domain that has one or more subdomains (A records)
    -s SUBDOMAINS  comma separated list of subdomains (A records) to update
    -i IP          IP address to set the subdomain(s) to. If blank namecheap
                   will use the callers public IP address.
    -t INTERVAL    set up a interval at which to run this. Uses bash sleep
                   format e.g. NUMBER[SUFFIX] where SUFFIX can be, s for
                   seconds (default), m for minutes, h for hours, d for days

EOF
}

EXIT_ON_ERROR=false

OPTIND=1 # Reset is necessary if getopts was used previously in the script.  It is a good idea to make this local in a function.
while getopts "hd:s:i:t:e" opt; do
  case "$opt" in
    h)
        show_help
        exit 0
        ;;
    d)  DOMAIN=$OPTARG
        ;;
    s)  SUBDOMAINS=$OPTARG
        ;;
    i)  IP=$OPTARG
        ;;
    t)  INTERVAL=$OPTARG
        ;;
    e)  EXIT_ON_ERROR=true
        ;;
    *)
        show_help >&2
        exit 1
        ;;
  esac
done
shift "$((OPTIND-1))" # Shift off the options and optional --.

# Check and set the password
: "${NC_DDNS_PASS:?Need to set the Dynamic DNS Password}"
PASS=$NC_DDNS_PASS

# Create the static URL
BASE_URL="https://dynamicdns.park-your-domain.com/update?domain=$DOMAIN&password=$PASS&ip=$IP"

if [ "$INTERVAL" ]; then
  # Run in a loop every inteval
  while [ : ]; do
    update
    sleep $INTERVAL
  done
else
  # Run once and exit
  update
fi
